server:
    port: 8813
spring:
    profiles:
        active: @activeProfile@
    cloud:
        sentinel:
            transport:
                dashboard: localhost:8080
                port: 8719
management:
    endpoints:
        web:
            cors:
                allowed-methods: '*'
