server:
    port: 8822
spring:
    profiles:
        active: @activeProfile@
#    application:
#        name: nacos-product-server
#    cloud:
#        nacos:
#            discovery:
#                server-addr: ${prop.nacos.config.server-addr}
