server:
    port: 8831
spring:
    profiles:
        active: @activeProfile@
    cloud:
      gateway:
        discovery:
          locator:
            # 是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能
            enabled: true
            # 默认服务名称必须大写 访问 true 小写即可访问
            lower-case-service-id: true
        routes:
        # 路由ID
          - id: product-server
          # 目标服务地址 注册中心服务ID
            uri: lb://nacos-product-server
            predicates:
              - Path=/product/**
